title: "내 블로그 제목"
description: "나의 생각과 투자, 엔지니어링 기록"
url: "https://내아이디.github.io"
author:
  name: "본인 이름"
  location: "South Korea"
  bio: "삼성 TV 하드웨어 엔지니어 & 투자자" # 선택 사항
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
